# Generated by Django 3.2.5 on 2022-12-07 16:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('dept_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=10, unique=True)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudID', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9999999999'. Up to 10 digits allowed. please specify country code with a '+' ", regex='^\\+?1?\\d{9,12}$')])),
                ('email', models.EmailField(max_length=254)),
                ('Name', models.CharField(max_length=100)),
                ('rollno', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.PositiveIntegerField()),
                ('grade', models.CharField(max_length=2)),
                ('student', models.ManyToManyField(to='College.Students')),
            ],
        ),
        migrations.CreateModel(
            name='examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='College.course')),
                ('marks', models.ManyToManyField(to='College.Marks')),
            ],
        ),
        migrations.CreateModel(
            name='dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=10)),
                ('batches', models.ManyToManyField(to='College.batch')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='Marks_Obtained',
            field=models.ManyToManyField(to='College.Marks'),
        ),
        migrations.AddField(
            model_name='batch',
            name='courses',
            field=models.ManyToManyField(to='College.course'),
        ),
        migrations.AddField(
            model_name='batch',
            name='studs',
            field=models.ManyToManyField(to='College.Students'),
        ),
    ]
